# Local Development

version: '3.9'
services:

#  flask:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    container_name: pr-flask-server
#    depends_on:
#      - database
#      - nginx
# #   ports:
# #     - "5000:5000"
#    restart: unless-stopped

  database:
    image: postgres:14
    container_name: pr-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data}
#    volumes:
#      - ${LOCAL_DATA:-./data}:/var/lib/postgresql/data

  nginx:
    image: nginx:1
    container_name: pr-nginx
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
    restart: unless-stopped

  vouch-proxy:
    container_name: pr-vouch-proxy
    image: fabrictestbed/vouch-proxy:0.27.1
    ports:
      - 9090:9090
    volumes:
      - ./vouch:/config
    restart: unless-stopped