# Local Development

version: '3.9'
services:

  database:
    image: postgres:14
    container_name: pr-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data}
#    volumes:
#      - ${LOCAL_DATA:-./data}:/var/lib/postgresql/data
