# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PeopleLong(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, people_id: str=None, cilogon_uid: str=None, name: str=None, roles: List[str]=None, projects: List[str]=None):  # noqa: E501
        """PeopleLong - a model defined in Swagger

        :param people_id: The people_id of this PeopleLong.  # noqa: E501
        :type people_id: str
        :param cilogon_uid: The cilogon_uid of this PeopleLong.  # noqa: E501
        :type cilogon_uid: str
        :param name: The name of this PeopleLong.  # noqa: E501
        :type name: str
        :param roles: The roles of this PeopleLong.  # noqa: E501
        :type roles: List[str]
        :param projects: The projects of this PeopleLong.  # noqa: E501
        :type projects: List[str]
        """
        self.swagger_types = {
            'people_id': str,
            'cilogon_uid': str,
            'name': str,
            'roles': List[str],
            'projects': List[str]
        }

        self.attribute_map = {
            'people_id': 'people_id',
            'cilogon_uid': 'cilogon_uid',
            'name': 'name',
            'roles': 'roles',
            'projects': 'projects'
        }
        self._people_id = people_id
        self._cilogon_uid = cilogon_uid
        self._name = name
        self._roles = roles
        self._projects = projects

    @classmethod
    def from_dict(cls, dikt) -> 'PeopleLong':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The People_long of this PeopleLong.  # noqa: E501
        :rtype: PeopleLong
        """
        return util.deserialize_model(dikt, cls)

    @property
    def people_id(self) -> str:
        """Gets the people_id of this PeopleLong.


        :return: The people_id of this PeopleLong.
        :rtype: str
        """
        return self._people_id

    @people_id.setter
    def people_id(self, people_id: str):
        """Sets the people_id of this PeopleLong.


        :param people_id: The people_id of this PeopleLong.
        :type people_id: str
        """

        self._people_id = people_id

    @property
    def cilogon_uid(self) -> str:
        """Gets the cilogon_uid of this PeopleLong.


        :return: The cilogon_uid of this PeopleLong.
        :rtype: str
        """
        return self._cilogon_uid

    @cilogon_uid.setter
    def cilogon_uid(self, cilogon_uid: str):
        """Sets the cilogon_uid of this PeopleLong.


        :param cilogon_uid: The cilogon_uid of this PeopleLong.
        :type cilogon_uid: str
        """

        self._cilogon_uid = cilogon_uid

    @property
    def name(self) -> str:
        """Gets the name of this PeopleLong.


        :return: The name of this PeopleLong.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PeopleLong.


        :param name: The name of this PeopleLong.
        :type name: str
        """

        self._name = name

    @property
    def roles(self) -> List[str]:
        """Gets the roles of this PeopleLong.


        :return: The roles of this PeopleLong.
        :rtype: List[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles: List[str]):
        """Sets the roles of this PeopleLong.


        :param roles: The roles of this PeopleLong.
        :type roles: List[str]
        """

        self._roles = roles

    @property
    def projects(self) -> List[str]:
        """Gets the projects of this PeopleLong.


        :return: The projects of this PeopleLong.
        :rtype: List[str]
        """
        return self._projects

    @projects.setter
    def projects(self, projects: List[str]):
        """Sets the projects of this PeopleLong.


        :param projects: The projects of this PeopleLong.
        :type projects: List[str]
        """

        self._projects = projects
